### PR TITLE
Added docs for adding index with indexType on MySQL

### PR DESCRIPTION
**Pull request by douglasjunior**
Related to https://github.com/tgriesser/knex/pull/2890

### CODE REVIEW

**Comment by kibertoad** [comment]
Thank you! Could you please remove generated files from PR? We regenerate them before release.

**Comment by douglasjunior** [comment]
I thought I should build before, sorry.

**Comment by kibertoad** [comment]
np ;)

**Comment by douglasjunior** [comment]
Done.

**Comment by kibertoad** [comment]
Awesome, thank you very much! We'll merge it after 0.16.0 is released.

**Pull request merged**
