### PR TITLE
Added docs for custom migration sources

### PR DESCRIPTION
**Pull request by JakeGinnivan**
Docs for https://github.com/tgriesser/knex/pull/2775

### CODE REVIEW

**Comment by kibertoad** [comment]
@elhigu Shouldn't this be merged now that next version with this functionality is out?

**Comment by elhigu** [comment]
No, only after real release.

**Comment by elhigu** [comment]
This could have more complete code example in cook book wiki.

**Comment by JakeGinnivan** [comment]
@elhigu where is that. Happy to try and get one in there.

**Comment by elhigu** [comment]
It is in https://github.com/tgriesser/knex/wiki

**Pull request merged**
