### PR TITLE
Fixes broken links

### PR DESCRIPTION
**Pull request by bnchdrff**
Starting from https://github.com/knex/documentation/pull/465 I fixed the rest of the broken internal links.

### CODE REVIEW

**Comment by CodingItWrong** [comment]
I think this would be good to merge; it would help me as a new user navigate the docs more easily.

**Comment by OlivierCavadenti** [comment]
Fixe in other PR (sry :x)

**Comment by bnchdrff** [comment]
@OlivierCavadenti they're still broken - for example in `src/guide/query-builder`:
image
that `a WHERE clause` link is broken

I can rebase if that's ok w/ you?

**Comment by bnchdrff** [comment]
Also thank you so much for doing PR reviews!!!

**Comment by OlivierCavadenti** [comment]
Oups... sorry. Can you made another PR, ping me and I will review.

**Pull request closed without merging**
