### PR TITLE
Updating port

### PR DESCRIPTION
**Pull request by Keyukemi**
The default port of Postgres is 5432. It was 3306 in the docs, but beginners might not know this, and so it leads to errors in their code when trying to use Knex.js. 

You can see more information [here](https://github.com/Dolibarr/dolibarr/issues/8236) and [here](https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/rds-default-port.html)

### CODE REVIEW

**Comment by kibertoad** [comment]
can you please remove the dsstore file?

**Comment by Keyukemi** [comment]
the DS_Store file has been removed

**Review by kibertoad — APPROVED** [review]

**Comment by kibertoad** [comment]
thanks!

**Comment by tkrotoff** [comment]
The .DS_Store is still present: 

image

https://github.com/knex/documentation/blob/main/.DS_Store

**Pull request merged**
