### PR TITLE
Fix typo for datetime type

### PR DESCRIPTION
**Pull request by vieiralucas**

### CODE REVIEW

**Comment by vieiralucas** [comment]
Hello? @tgriesser @bendrucker @eilgin @wubzz @ricardograca @rhys-vdw

**Comment by wubzz** [comment]
What is the reason for wanting to change this?

I just want to understand since technically both are valid syntaxes in knex, theres `.dateTime` and `.datetime`.

**Comment by elhigu** [comment]
I like that lower case version better :p

**Comment by kibertoad** [comment]
@elhigu Do you think we should merge this?

**Comment by vieiralucas** [comment]
@wubzz I didn't know knex supported both syntaxes. IMHO the docs should be consistent and choose one of the syntaxes or explain better to the user that are two possible syntaxes.

**Comment by kibertoad** [comment]
@vieiralucas If possible, could you please remove all the changes from build/ files from this PR? We typically rebuild documentation before releasing new versions, there are some changes that are too early to be published.

**Comment by kibertoad** [comment]
(build and index, everything that is generated)

**Comment by elhigu** [comment]
> @vieiralucas If possible, could you please remove all the changes from build/ files from this PR? We typically rebuild documentation before releasing new versions, there are some changes that are too early to be published.

Also many times there has been syntax errors in some of the documentation pull requests, so I usually test one rebuilding docs after merging every PR. Thats another reason, why I like to do that stuff only during the release.

**Comment by kibertoad** [comment]
Thank you!

**Pull request merged**
