### PR TITLE
Fix custom migration sources typos

### PR DESCRIPTION
**Pull request by bgschiller**

### CODE REVIEW

**Comment by kibertoad** [comment]
Thanks!

**Comment by ben-turner** [comment]
I commented in #171 but going to add it here as well—sorry for anyone getting double pings. 

Looks like this change has never been deployed. The live documentation still says "Migraiton".

**Comment by elhigu** [comment]
Last knex version was 0.16.3 — 19 Dec, 2018, documentation was built that day. So this will not get built before next release.

**Comment by ben-turner** [comment]
Really? There's no way to update or fix documentation in between library releases? That seems... less than ideal.

**Comment by elhigu** [comment]
of course it is possible, but its usually not really worth of effort

**Pull request merged**
