### PR TITLE
fix: explain how to use returning parameter for insert and update operations

### PR DESCRIPTION
**Pull request by chachan**
This closes https://github.com/tgriesser/knex/issues/1547

### CODE REVIEW

**Comment by kibertoad** [comment]
@chachan Ping?..

**Comment by chachan** [comment]
hey. Sorry, I missed this, I'll take care. Would it need to list of which engines do support that functionally of just as an advice to developers?

**Comment by kibertoad** [comment]
@chachan I think any details that you are aware of would be useful for developers; is there actual different on engine level? I thought that PostgreSQL support it in general and MySQL doesn't support it at all, is there a more granular difference?

**Comment by chachan** [comment]
@kibertoad I don't know those details at the moment but I can check docs of engines to gather information that might be useful

**Comment by kibertoad** [comment]
@chachan Thank you so much! ❤️

**Pull request merged**
