### PR TITLE
Add documentation for enum existingType

### PR DESCRIPTION
**Pull request by ekeric13**
Related to this feature: https://github.com/tgriesser/knex/pull/2719

Snapshot of what this looks like:
screen shot 2018-11-06 at 4 07 04 pm

### CODE REVIEW

**Comment by ekeric13** [comment]
Should I also commit the build? Or do we just change the react components?

**Comment by elhigu** [comment]
> Should I also commit the build? 

No, we'll build everything when releasing new version. If all changes would also commit build files it would be nightmare while merging PRs in.

**Comment by ekeric13** [comment]
Updated version:
screen shot 2018-11-08 at 8 50 09 pm

**Comment by ekeric13** [comment]
We can change it to irrelevant if you think that is more clear. They are essentially synonymous.

**Pull request merged**
