### PR TITLE
Revert "add description returning method on MySQL and SQlite"

### PR DESCRIPTION
**Pull request by elhigu**
Reverts knex/documentation#141 which just added invalid and contradicting information.

### CODE REVIEW

**Comment by HurSungYun** [comment]
@elhigu my bad. I was confused because of this example maybe.

image

I believe mysql returns `[2]` by its protocol, so I think the phrase `Returns [2] in "mysql", "sqlite";` should be removed since its results are not made by `.returning` method.

**Comment by elhigu** [comment]
I believe (didn't check from docs page) that the part you quoted is from `.insert` documentation where it is important information to know what sqlite / mysql returns.

**Comment by HurSungYun** [comment]
that phrase exists in both `.insert` and `.returning` docs. I agree with you that information in `.insert` should be exists, but I doubt it when it comes to `.returning`

**Comment by HurSungYun** [comment]
please check this out

https://knexjs.org/#Builder-returning

**Comment by elhigu** [comment]
true, overall those parts could be written in a more clear manner

**Pull request merged**
