### PR TITLE
Migrate documentation to vitepress

### PR DESCRIPTION
**Pull request by stafyniaksacha**
This pull request is related to work made on https://github.com/knex/documentation/issues/391 and https://github.com/knex/documentation/issues/337 and https://github.com/knex/knex/pull/5121

Preview 🪄 https://stafyniaksacha.github.io/knex/

All the documentation and wiki content has been migrated to markdown with latest version (v1.0.7)

- I do not have made anything related with dialect SQL output selection, but we can do it easily with custom vue components and localstorage (as on the vuejs website for the composition/option api)
- We may want to discuss the documentation sections as well!
- We can also add a great search experience easily with https://docsearch.algolia.com/apply/ 
- A lot of small improvement can be made!
- CI is not set up
- linters are not set up
- Question remains against automatic changelog generation

### CODE REVIEW

**Comment by stafyniaksacha** [comment]
Any news @kibertoad @OlivierCavadenti @intech @vencho-mdp ?
I have contacted algolia to implement docsearch

**Review by OlivierCavadenti — APPROVED** [review]
it's ok, thanks for this work !!

**Comment by vencho-mdp** [comment]
@stafyniaksacha Check out the PR I did to your repo to implement Dialect Options :)

**Comment by stafyniaksacha** [comment]
@vencho-mdp thanks for the ping, I've dug a bit more but still have issue (more details in the original PR)

**Comment by vencho-mdp** [comment]
what's missing to merge this PR?

**Comment by stafyniaksacha** [comment]
I have setup the DocSearch (with algolia) https://stafyniaksacha.github.io/knex/

The only thing mission from previous version is the SQL output, but we can find a way latter, what do you think?

**Comment by stafyniaksacha** [comment]
@vencho-mdp I finally find a way to get those output! I generate them with a vite plugin at built time!

> https://stafyniaksacha.github.io/knex/guide/ref.html#usage

**Comment by vencho-mdp** [comment]
@stafyniaksacha  Oh, that's pretty clever, and since you generate them at built time, I guess it has a positive impact on the performance. However, some of the SQL code generated could not be ever shown, so you might be making unnecessary computations, but I think the tradeoff is great though. Great Job!

**Pull request merged**
