### PR TITLE
Update schema.js

### PR DESCRIPTION
**Pull request by machineghost**
This commit corrects the missing documentation noted here: https://github.com/knex/knex/issues/2945 

It clarifies that because Knex's PostgreSQL integration doesn't support float precision, the Knex `float` method will result in a PostgreSQL "real" number column type.

### CODE REVIEW

**Comment by machineghost** [comment]
Is there anything I can do to help facilitate this?  It's a pure documentation fix (in theory easy to merge) but it's been sitting for two months.

**Comment by kibertoad** [comment]
Sorry, my brain doesn't work lately. @briandamaged does the change make sense to you?

**Comment by briandamaged** [comment]
I'm not super familiar w/ the specific details of the PostgresQL dialect.  Perhaps @elhigu know?

(I can also dig into the PostgresQL code either tonight or tomorrow.  I'd just like to confirm our understanding of the PostgresQL limitations before we document them)

**Comment by elhigu** [comment]
Yeah, this is kind of correct `float()` column creates postgres REAL type and `.double()` DOUBLE PRECICION types  https://www.postgresql.org/docs/9.1/datatype-numeric.html

**Comment by machineghost** [comment]
This is *definitely* scope creep, but I've noticed that this bug is really a more specific case of a far more general problem.  Let's say I want to use the Knex schema creation method ____ with database ____: what column type will I actually create in that database?

That can be a very reasonable question to ask for any number of permutations ... but for the most part the documentation doesn't address it (certainly not in any systematic way).

Would there be any interest in adding some sort of table (or set of tables) to the documentation which map Knex methods to types, or in adding to the documentation for each method itself to show what type they'll create in each DB?  A cursory look at the source code suggest this data could mostly be auto-generated (to help keep it current without being a maintenance hassle).

**Pull request closed without merging**
