### PR TITLE
Fix "migraiton" typo

### PR DESCRIPTION
**Pull request by florenzo-42**
Just ran `sed`, can't build it (even on master) as the scripts are broken but shouldn't break anything.  
Nice package btw

### CODE REVIEW

**Comment by florenzo-42** [comment]
Done :-)

**Comment by kibertoad** [comment]
Thank you!

**Comment by elhigu** [comment]
This seemed to just change index.html. AFAIK that is automatiacally generated file, which should not be changed.

**Comment by kibertoad** [comment]
@elhigu I tried searching through the repo and didn't find `migraiton` word anywhere, and I assume you rebuilt the file the last time?

**Comment by elhigu** [comment]
Yep, it shows as changed every time when I build docs... I'm not with laptop, where  got knex stuff installed to check it out if it is built only partly or what...

**Comment by elhigu** [comment]
and I believe that this might be the code that generates the file: https://github.com/knex/documentation/blob/4ba79be72b89f2524ce4441695030f0b67919edd/scripts/server.js#L71

**Comment by kibertoad** [comment]
Right, then judging by the code, part of index.html does seem to be included as-is.

**Comment by elhigu** [comment]
nope.. judgng by code, the whole index.html is regenerated and contents are rendered with react by rendering component called Documentation.jsx... so reverting this. Correct place to fix that line in ins sections/migrations.js or something like that.

**Comment by elhigu** [comment]
https://github.com/knex/documentation/blob/4ba79be72b89f2524ce4441695030f0b67919edd/sections/migrations.js#L323

**Comment by kibertoad** [comment]
Are you sure this needs to be reverted? migrations.js seems to be correct already, index.html is not. How is this making anything worse?

**Comment by kibertoad** [comment]
`Line 323 in 4ba79be` seems outdated.

**Comment by elhigu** [comment]
Yep, it was fixed in this PR https://github.com/knex/documentation/pull/169

**Comment by ben-turner** [comment]
I hate to necro old PRs like this, but it looks like #169 has never been built/deployed. The documentation still contains the typo.

**Pull request merged**
