### PR TITLE
add port option to connection

### PR DESCRIPTION
**Pull request by Ahacad**
ref #323

### CODE REVIEW

**Comment by kibertoad** [comment]
Could you please replace `your_port` with more realistic param, which usually would be a number?

**Comment by Ahacad** [comment]
using mysql default 3306 port now as an example

**Comment by kibertoad** [comment]
@Ahacad TS types expect number to be passed as opposed to number-like string. Sorry for being ambiguous, could you please change the example to actual numbers?

**Comment by Ahacad** [comment]
fixed

**Comment by Ahacad** [comment]
fixed

**Review by kibertoad — APPROVED** [review]

**Pull request merged**
