### PR TITLE
Documentation fix errors #351

### LINKED ISSUE #351: Fix documentation errors
Hi,

With 0.95.12 a lot of documentation is added, I re-read it and I see some errors (';' errors in views, 'const' errors, date errors...).

So @kibertoad I plan to fix them all soon to refresh it. If you are okay, I want to change the order in the sidebard too, especially in Schema Builder section (group schema, table and views functions together).

### PR DESCRIPTION
**Pull request by OlivierCavadenti**
Refresh the current documentation with

- Fix Date.UTC error (https://github.com/knex/documentation/issues/258)
- Fix all 'const' errors.
- Fix ';' errors.
- Add orWhere mention.
- Add geometry/geography/point methods.
- Split Schema Builder in sections (schema, table, view) to be more clear. I group methods in each section.
- Some typos and sidebar links fixes.

Closes #351 
Closes https://github.com/knex/knex/issues/3990

### CODE REVIEW

**Comment by OlivierCavadenti** [comment]
By the way just to say, it's seems we have doc for partial index + upsert published but commits are in master, in 1.0.0
It's not very important, but maybe we can have issues about that (upsert function not available for ex).

**Comment by kibertoad** [comment]
@OlivierCavadenti That's rather unfortunate. Were they only merged, or also built into html?

**Comment by OlivierCavadenti** [comment]
> @OlivierCavadenti That's rather unfortunate. Were they only merged, or also built into html?

Sry I remove my comment. It's seems is good after all ^^.

**Comment by OlivierCavadenti** [comment]
I finally split this in small PRs (some fixes are already merged). I think is better (and less necessary) to dont do the rework of sidebar now

**Pull request closed without merging**
